/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Exer4;

import javax.swing.JOptionPane;

/**
 *
 * @author Leonardo
 */
public class GUI_Pedido extends javax.swing.JFrame {
    ControlePedido cp = new ControlePedido();
    public Cliente cli;
    public Cliente getCli() {
        return cli;
    }

    public void setCli(Cliente cli) {
        this.cli = cli;
    }
    public GUI_Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValorPizza = new javax.swing.JTextField();
        cbxTipo = new javax.swing.JComboBox<>();
        cbxQt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbxTipo2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbxQt2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtValorBebida = new javax.swing.JTextField();
        cbxNome = new javax.swing.JComboBox<>();
        cbxSabor = new javax.swing.JComboBox<>();
        btnFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("GUI_Pedido");

        lblNome.setText("Olá");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Pizza");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Bebida");

        jLabel4.setText("Sabor");

        jLabel5.setText("Tipo");

        jLabel6.setText("Quantidade");

        jLabel7.setText("Valor");

        txtValorPizza.setEnabled(false);

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Broto" }));
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });

        cbxQt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbxQt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxQtActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome");

        jLabel9.setText("Tipo");

        cbxTipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lata", "2 Litros" }));
        cbxTipo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipo2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Quantidade");

        cbxQt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cbxQt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxQt2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor");

        txtValorBebida.setEnabled(false);

        cbxNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca-Cola", "Água", "Guarana" }));
        cbxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomeActionPerformed(evt);
            }
        });

        cbxSabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portuguesa", "Marguerita", "Chocolate" }));
        cbxSabor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxSaborMouseClicked(evt);
            }
        });
        cbxSabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSaborActionPerformed(evt);
            }
        });

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxSabor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxQt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(6, 6, 6)
                                .addComponent(txtValorPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxQt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(txtValorBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNome))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtValorPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxQt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxSabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtValorBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxQt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblNome.setText("Olá, " +cli.getNome()+ " seja bem vindo!");
    }//GEN-LAST:event_formWindowOpened



    private void cbxSaborMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxSaborMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxSaborMouseClicked

    private void cbxSaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSaborActionPerformed
        // TODO add your handling code here:
        int val;
        if (cbxTipo.getSelectedIndex() == 0) {
            val = 35 * Integer.parseInt(cbxQt.getSelectedItem().toString());
        } else {
            val = 12* Integer.parseInt(cbxQt.getSelectedItem().toString());
        }
        txtValorPizza.setText(Integer.toString(val));
    }//GEN-LAST:event_cbxSaborActionPerformed

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        // TODO add your handling code here:
          int val;
        if (cbxTipo.getSelectedIndex() == 0) {
            val = 35 * Integer.parseInt(cbxQt.getSelectedItem().toString());
        } else {
            val = 12* Integer.parseInt(cbxQt.getSelectedItem().toString());
        }
        txtValorPizza.setText(Integer.toString(val));
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void cbxQtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxQtActionPerformed
        // TODO add your handling code here:
         int val;
        if (cbxTipo.getSelectedIndex() == 0) {
            val = 35 * Integer.parseInt(cbxQt.getSelectedItem().toString());
        } else {
            val = 12* Integer.parseInt(cbxQt.getSelectedItem().toString());
        }
        txtValorPizza.setText(Integer.toString(val));
    }//GEN-LAST:event_cbxQtActionPerformed

    private void cbxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomeActionPerformed
        // TODO add your handling code here:
         int val;
        if (cbxTipo2.getSelectedIndex() == 0) {
            val = 3 * Integer.parseInt(cbxQt2.getSelectedItem().toString());
        } else {
            val = 8* Integer.parseInt(cbxQt2.getSelectedItem().toString());
        }
        txtValorBebida.setText(Integer.toString(val));
    }//GEN-LAST:event_cbxNomeActionPerformed

    private void cbxTipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipo2ActionPerformed
        // TODO add your handling code here:
         int val;
        if (cbxTipo2.getSelectedIndex() == 0) {
            val = 3 * Integer.parseInt(cbxQt2.getSelectedItem().toString());
        } else {
            val = 8* Integer.parseInt(cbxQt2.getSelectedItem().toString());
        }
        txtValorBebida.setText(Integer.toString(val));
    }//GEN-LAST:event_cbxTipo2ActionPerformed

    private void cbxQt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxQt2ActionPerformed
        // TODO add your handling code here:
         int val;
        if (cbxTipo2.getSelectedIndex() == 0) {
            val = 3 * Integer.parseInt(cbxQt2.getSelectedItem().toString());
        } else {
            val = 8* Integer.parseInt(cbxQt2.getSelectedItem().toString());
        }
        txtValorBebida.setText(Integer.toString(val));
    }//GEN-LAST:event_cbxQt2ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        cp.calcTotalPed(Double.parseDouble(txtValorPizza.getText()),Double.parseDouble(txtValorBebida.getText()));
        JOptionPane.showMessageDialog(null, "O seu pedido demorará aproximadamente "+cp.calcTempoPed()+" minutos");
        cp.pedFinalizar(cbxSabor.getSelectedItem().toString(),cbxTipo.getSelectedItem().toString(),Integer.parseInt(cbxQt.getSelectedItem().toString()),Double.parseDouble(txtValorPizza.getText()),cbxNome.getSelectedItem().toString(),cbxTipo2.getSelectedItem().toString(),Integer.parseInt(cbxQt2.getSelectedItem().toString()),Double.parseDouble(txtValorBebida.getText()), cli);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        int val;
        if (cbxTipo2.getSelectedIndex() == 0) {
            val = 3 * Integer.parseInt(cbxQt2.getSelectedItem().toString());
        } else {
            val = 8* Integer.parseInt(cbxQt2.getSelectedItem().toString());
        }
        txtValorBebida.setText(Integer.toString(val));
        if (cbxTipo.getSelectedIndex() == 0) {
            val = 35 * Integer.parseInt(cbxQt.getSelectedItem().toString());
        } else {
            val = 12* Integer.parseInt(cbxQt.getSelectedItem().toString());
        }
        txtValorPizza.setText(Integer.toString(val));
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Pedido().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JComboBox<String> cbxNome;
    private javax.swing.JComboBox<String> cbxQt;
    private javax.swing.JComboBox<String> cbxQt2;
    private javax.swing.JComboBox<String> cbxSabor;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JComboBox<String> cbxTipo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtValorBebida;
    private javax.swing.JTextField txtValorPizza;
    // End of variables declaration//GEN-END:variables
}
